/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/centrepoint.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/centrepoint.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.005']} position={[0, 3.2, 0]} scale={[6.4, 2.5, 6.4]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.004']} position={[0.006, 3.3, 0]} scale={[24, 0.038, 24]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.012']} position={[0, 0.2, 0]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.013']} position={[2.5, 0.2, -2.5]} rotation={[0, 0, -Math.PI]} scale={[-0.05, -1.5, -0.05]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.013']} position={[-2.5, 0.2, 2.5]} rotation={[-Math.PI, 0, 0]} scale={[-0.05, -1.5, -0.05]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.013']} position={[2.5, 0.2, 2.5]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.013']} position={[-2.5, 0.2, -2.5]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.05, 1.5, 0.05]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.010']} position={[0, 0.2, 1.667]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.010']} position={[0, 0.2, -1.667]} scale={[2.55, 1.5, 0.05]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.010']} position={[0, 0.2, 0.833]} scale={[2.55, 1.5, 0.05]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.010']} position={[0, 0.2, -0.833]} scale={[2.55, 1.5, 0.05]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.010']} position={[0, 0.2, 0]} scale={[2.55, 1.5, 0.05]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.011']} position={[1.667, 0.2, 0]} rotation={[0, Math.PI / 2, 0]} scale={[2.55, 1.5, 0.05]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.011']} position={[-1.667, 0.2, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.011']} position={[0.833, 0.2, 0]} rotation={[0, Math.PI / 2, 0]} scale={[2.55, 1.5, 0.05]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.011']} position={[-0.833, 0.2, 0]} rotation={[0, Math.PI / 2, 0]} scale={[2.55, 1.5, 0.05]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.011']} position={[0, 0.2, 0]} rotation={[0, Math.PI / 2, 0]} scale={[2.55, 1.5, 0.05]} />
      <mesh geometry={nodes.level3.geometry} material={materials['Material.009']} position={[0, 3.2, 0]} scale={[1.457, 1, 1.457]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.008']} position={[0, 10.143, 0]} scale={[1.3, 0.975, 1.3]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.002']} position={[0, 8.843, 0]} rotation={[0, -Math.PI / 8, 0]} scale={[15.6, 0.325, 14.56]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[0, 7.543, 0]} scale={[20.8, 0.65, 20.8]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.014']} />
    </group>
  )
}

useGLTF.preload('/centrepoint.glb')
