/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/wisetech.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Wisetech(props) {
  const { nodes, materials } = useGLTF('/models/wisetech.glb')
  return (
    <group {...props} dispose={null} scale={[0.7,0.7,0.7]} position={[0,0,3]} rotation={[0, -Math.PI/2, 0]}>
			<RigidBody>

      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.002']} position={[-3.4, 1.45, -1.5]} scale={[0.4, 0.1, 0.75]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.003']} position={[-3, 0, -0.5]} scale={[0.05, 1.25, 0.05]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[-3, 1.5, -2]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.003']} position={[-3, 0, 1]} scale={[0.05, 1.25, 0.05]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.003']} position={[-3, 0, 2.5]} scale={[0.05, 1.25, 0.05]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.003']} position={[-3, 0, 4]} scale={[0.05, 1.25, 0.05]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.001']} position={[-1, 0.8, -3.775]} scale={[0.5, 0.133, 0.2]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.001']} position={[1, 0.8, -3.775]} scale={[0.5, 0.133, 0.2]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.001']} position={[-2.87, 0.8, 0.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.4, 0.133, 0.16]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.001']} position={[-2.87, 0.8, 1.75]} rotation={[0, Math.PI / 2, 0]} scale={[0.4, 0.133, 0.16]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.001']} position={[-2.87, 0.8, 3.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.4, 0.133, 0.16]} />
      <mesh geometry={nodes.left.geometry} material={materials.Material} position={[-1.7, 1.84, -4]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.left001.geometry} material={materials.Material} position={[-3, 1.25, -3.7]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.navy} scale={[3, 2, 4]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-1, 1.8, -3.95]} rotation={[Math.PI, 0, Math.PI]} scale={[0.5, 0.4, 0.2]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[1, 1.8, -3.95]} rotation={[Math.PI, 0, Math.PI]} scale={[0.5, 0.4, 0.2]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-3, 2, -2.75]} rotation={[0, -Math.PI / 2, 0]} scale={[0.4, 0.32, 0.16]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[-3, 2, -1.25]} rotation={[0, -Math.PI / 2, 0]} scale={[0.4, 0.32, 0.16]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[-3, 2, 0.25]} rotation={[0, -Math.PI / 2, 0]} scale={[0.4, 0.32, 0.16]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.001']} position={[-3, 2, 1.75]} rotation={[0, -Math.PI / 2, 0]} scale={[0.4, 0.32, 0.16]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[-3, 2, 3.25]} rotation={[0, -Math.PI / 2, 0]} scale={[0.4, 0.32, 0.16]} />
			</RigidBody>
    </group>
  )
}

useGLTF.preload('/models/wisetech.glb')
