/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/university.glb -o ./src/models/University.tsx -t --shadows 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { INITIAL_LR_POSITION, NUM_PAGES, SEGMENT_LENGTH } from '../../constants';
import useModelStore from '../../store/useModelStore';
import { useControls } from 'leva';


export function Model() {
  const { scene } = useGLTF('models/light-rail.glb');
	const lightRail = useRef<THREE.Object3D>(null);
	const { setLightRail } = useModelStore();

	// const scroll = useScroll();

	useEffect(() => {
		if (lightRail && lightRail.current) {
			setLightRail(lightRail as React.RefObject<THREE.Object3D<THREE.Object3DEventMap>>);
		}
	} ,[lightRail, setLightRail]);

	const {
		lightRailControls,
	} = useControls({ 
		lightRailControls: true
	})
	
	useEffect(() => {
		if (lightRail.current) {
			lightRail.current.position.set(
				INITIAL_LR_POSITION.x,
				INITIAL_LR_POSITION.y,
				INITIAL_LR_POSITION.z,
			);
		}
	}, [lightRail])

	useFrame(() => {
		if (!lightRailControls) return;
		console.log(NUM_PAGES * SEGMENT_LENGTH * scroll.offset)
		if (lightRail.current) {
			lightRail.current.position.lerp(new THREE.Vector3(
				lightRail.current.position.x,
				lightRail.current.position.y, 
				0 // NUM_PAGES * SEGMENT_LENGTH * scroll.offset
			), 0.5);
		}
	});

	return (
		<primitive
			ref={lightRail}
			object={ scene }
			scale={ 0.05 }
    />
	)
}

useGLTF.preload('models/light-rail.glb')
