/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/university.glb -o ./src/models/University.tsx -t --shadows 
*/

import * as THREE from 'three'
import { JSX, useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('models/map.glb');

	const grassRef = useRef<THREE.Mesh>(null);

	const [
		ainsworthTexture,
		gardenTexture,
		redcenterTexture,
		scientiaTexture,
		terrainTexture
	] = useTexture([
		'./textures/uni-ainsworth.jpg',
		'./textures/uni-garden.jpg',
		'./textures/uni-redcenter.jpg',
		'./textures/uni-scientia.jpg',
		'./textures/uni-terrain.jpg'
	])
	ainsworthTexture.flipY = false;
	gardenTexture.flipY = false;
	redcenterTexture.flipY = false;
	scientiaTexture.flipY = false;
	terrainTexture.flipY = false;
	
	return (
			<group rotation={[0, Math.PI / 2, 0]}>
				<mesh geometry={ nodes.ainsworth.geometry }  position={ nodes.ainsworth.position} rotation={ nodes.ainsworth.rotation}>
						<meshBasicMaterial map={ ainsworthTexture } />
				</mesh>
				<mesh geometry={ nodes.redcenter.geometry } position={ nodes.redcenter.position} rotation={ nodes.redcenter.rotation}>
						<meshBasicMaterial map={ redcenterTexture } />
				</mesh>
				<mesh geometry={ nodes.scientia.geometry } position={ nodes.scientia.position} rotation={ nodes.scientia.rotation}>
						<meshBasicMaterial map={ scientiaTexture }/>
				</mesh>
				<mesh geometry={ nodes.garden.geometry } position={ nodes.garden.position} rotation={ nodes.garden.rotation}>
						<meshBasicMaterial map={ gardenTexture } />
				</mesh>
				<mesh geometry={ nodes.terrain.geometry } position={ nodes.terrain.position} rotation={ nodes.terrain.rotation}>
						<meshBasicMaterial map={ terrainTexture } />
				</mesh>
				<mesh geometry={ nodes.grass.geometry } position={ nodes.grass.position} rotation={ nodes.grass.rotation} ref={grassRef}>
						<meshBasicMaterial map={ terrainTexture } />
				</mesh>
				<mesh geometry={ nodes.globe.geometry } position={ nodes.globe.position} rotation={ nodes.globe.rotation} >
						<meshStandardMaterial color={"#333333"} />
				</mesh>
			</group>
	)
}

useGLTF.preload('models/map.glb')
