/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ainsworth.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ainsworth(props) {
  const { nodes, materials } = useGLTF('/models/ainsworth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.top001.geometry} material={materials.Material} position={[-0.462, 2.004, 3.087]} scale={[0.714, 0.7, 1.165]} />
      <mesh geometry={nodes.roof1.geometry} material={materials['Material.001']} position={[-0.07, 1.836, 1.4]} scale={[0.712, 0.038, 0.817]} />
      <mesh geometry={nodes.extension.geometry} material={materials['Material.002']} position={[-0.077, 5.504, 1.4]} scale={[0.714, 1, 0.571]} />
      <mesh geometry={nodes.base.geometry} material={materials['Material.013']} position={[-0.08, 1, -0.16]} scale={[2.786, 1, 3]} />
      <mesh geometry={nodes.window.geometry} material={materials['Material.014']} position={[-1.879, 0.722, 2.8]} rotation={[0, 0, -Math.PI]} scale={[-0.579, -0.271, -0.09]} />
      <mesh geometry={nodes.roof1001.geometry} material={materials['Material.001']} position={[-0.07, 5.625, 1.4]} scale={[0.713, 0.038, 0.525]} />
      <mesh geometry={nodes.door.geometry} material={materials['Material.011']} position={[-0.473, 0.7, 2.9]} scale={[0.846, 1, 1]} />
      <mesh geometry={nodes.door001.geometry} material={materials['Material.012']} position={[2.56, 0.677, 1.82]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.967, 1]} />
      <mesh geometry={nodes.a1.geometry} material={materials['Material.004']} position={[2.497, 2.799, 0.736]} rotation={[0, 1.571, 0]} scale={[-1.129, -0.312, -0.1]} />
      <mesh geometry={nodes.b1.geometry} material={materials['Material.005']} position={[2.49, 2.45, 0.736]} rotation={[-Math.PI, 1.571, 0]} scale={[0.672, 0.735, 1]} />
      <mesh geometry={nodes.b2.geometry} material={materials['Material.005']} position={[2.49, 3.148, 0.736]} rotation={[-Math.PI, 1.571, 0]} scale={[0.672, 0.735, 1]} />
      <mesh geometry={nodes.a2.geometry} material={materials['Material.004']} position={[2.497, 3.497, 0.736]} rotation={[0, 1.571, 0]} scale={[-1.129, -0.312, -0.1]} />
      <mesh geometry={nodes.b3.geometry} material={materials['Material.005']} position={[2.49, 3.846, 0.736]} rotation={[-Math.PI, 1.571, 0]} scale={[0.672, 0.735, 1]} />
      <mesh geometry={nodes.b4.geometry} material={materials['Material.005']} position={[2.49, 4.543, 0.736]} rotation={[-Math.PI, 1.571, 0]} scale={[0.672, 0.735, 1]} />
      <mesh geometry={nodes.a3.geometry} material={materials['Material.004']} position={[2.497, 4.194, 0.736]} rotation={[0, 1.571, 0]} scale={[-1.129, -0.312, -0.1]} />
      <mesh geometry={nodes.a4.geometry} material={materials['Material.004']} position={[2.497, 4.892, 0.736]} rotation={[0, 1.571, 0]} scale={[-1.129, -0.312, -0.1]} />
      <mesh geometry={nodes.b5.geometry} material={materials['Material.005']} position={[2.49, 5.241, 0.736]} rotation={[-Math.PI, 1.571, 0]} scale={[0.672, 0.735, 1]} />
      <mesh geometry={nodes.balcony2.geometry} material={materials['Material.006']} position={[-2.584, 4.121, 1.035]} />
      <mesh geometry={nodes.balcony3.geometry} material={materials['Material.006']} position={[-2.584, 2.821, 1.035]} />
      <mesh geometry={nodes.bottom.geometry} material={materials['Material.003']} position={[-3.169, 1.95, 0.492]} scale={[1, 1, 1.063]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.008']} position={[-1.884, 4.121, 0.755]} scale={[0.5, 1, 0.375]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.009']} position={[-2.034, 2.821, 0.755]} scale={[0.5, 1, 0.375]} />
      <mesh geometry={nodes.bottom001.geometry} material={materials['Material.003']} position={[-3.169, 5.43, 0.492]} scale={[1, 1, 1.063]} />
      <mesh geometry={nodes.cafe.geometry} material={materials['Material.010']} position={[1.5, 1, 2.269]} scale={[1.055, 1, 0.9]} />
    </group>
  )
}

useGLTF.preload('/models/ainsworth.glb')
