/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/anita.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Anita(props) {
  const { nodes, materials } = useGLTF('/models/anita.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.m_cylinder} position={[-2.35, 0, 1]} scale={[4, 10, 4]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.m_cylinder} position={[-1.5, 0, 1]} scale={[4, 10, 4]} />
      <mesh geometry={nodes.Door.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.m_panel} position={[0.926, 3, 0.36]} scale={[20, 4, 6]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Material} position={[-0.199, 3, -0.125]} scale={[0.15, 1.25, 0.15]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Material} position={[0.051, 3, -0.125]} scale={[0.15, 1.25, 0.15]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Material} position={[0.301, 3, -0.125]} scale={[0.15, 1.25, 0.15]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.Material} position={[0.551, 3, -0.125]} scale={[0.15, 1.25, 0.15]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.Material} position={[1.301, 3, -0.125]} scale={[0.15, 1.25, 0.15]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.Material} position={[1.551, 3, -0.125]} scale={[0.15, 1.25, 0.15]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.Material} position={[1.801, 3, -0.125]} scale={[0.15, 1.25, 0.15]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.Material} position={[2.051, 3, -0.125]} scale={[0.15, 1.25, 0.15]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.005']} position={[-2.85, 1.5, -0.75]} scale={[2, 2.5, 2.5]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['m_cylinder.001']} position={[-3.47, 0, -1.5]} rotation={[0, -Math.PI / 8, 0]} scale={[4, 12, 4]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials['m_cylinder.002']} position={[-3.47, 0, 0]} rotation={[0, -Math.PI / 8, 0]} scale={[4, 12, 4]} />
    </group>
  )
}

useGLTF.preload('/models/anita.glb')
