/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/centrepoint.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Centrepoint(props) {
  const { nodes, materials } = useGLTF('/models/centrepoint.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.level3.geometry} material={materials['Material.002']} position={[0, 1.8, 0]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.005']} position={[0, 1.95, 0]} scale={[4.8, 2.525, 4]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.006']} position={[0, 7, 0]} scale={[16, 0.5, 16]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.007']} position={[0, 8, 0]} rotation={[0, -Math.PI / 8, 0]} scale={[12, 0.25, 11.2]} />
      <mesh geometry={nodes.level1.geometry} material={materials['Material.001']} scale={[1.75, 0.1, 1.75]} />
      <mesh geometry={nodes.level2.geometry} material={materials['Material.001']} position={[0, 1, 0]} />
      <mesh geometry={nodes.inner.geometry} material={materials['Material.003']} position={[0, 1, 0]} scale={[1.6, 0.8, 1.6]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.004']} position={[0, 1.9, 0]} scale={[18.4, 0.025, 18.4]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Material} position={[-0.599, 0.563, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.Material} position={[-0.864, 0.563, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Material} position={[-1.415, 0.563, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Material} position={[0.733, 0.563, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Material} position={[0.488, 0.563, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.Material} position={[1.432, 0.563, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.Material} position={[1.19, 0.563, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.Material} position={[1.19, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.Material} position={[0.952, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.Material} position={[0.488, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.Material} position={[0.25, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.Material} position={[-0.142, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials.Material} position={[-0.38, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials.Material} position={[-0.605, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials.Material} position={[-0.843, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.Material} position={[-1.209, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.Material} position={[-1.448, 1.438, 0]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.Material} position={[1.415, 1.438, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.bar.geometry} material={materials.Material} position={[0, 0.563, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[-0.008, 0.563, 0.591]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[-0.008, 0.563, 0.856]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Material} position={[-0.008, 0.563, 1.407]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[-0.008, 0.563, -0.741]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials.Material} position={[-0.008, 0.563, -0.496]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.Material} position={[-0.008, 0.563, -1.44]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials.Material} position={[-0.008, 0.563, -1.198]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.Material} position={[-0.008, 1.437, -1.198]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.Material} position={[-0.008, 1.437, -0.96]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials.Material} position={[-0.008, 1.437, -0.496]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials.Material} position={[-0.008, 1.437, -0.258]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials.Material} position={[-0.008, 1.437, 0.134]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.Material} position={[-0.008, 1.437, 0.372]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials.Material} position={[-0.008, 1.437, 0.597]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.Material} position={[-0.008, 1.437, 0.835]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials.Material} position={[-0.008, 1.437, 1.201]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials.Material} position={[-0.008, 1.437, 1.44]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials.Material} position={[-0.008, 1.437, -1.423]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.bar001.geometry} material={materials.Material} position={[-0.008, 0.563, -0.008]} rotation={[0, Math.PI / 2, 0]} scale={[0.05, 0.363, 1.675]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.008']} position={[0, 9, 0]} scale={[1, 0.75, 1]} />
    </group>
  )
}

useGLTF.preload('/models/centrepoint.glb')
