/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/clancy.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Clancy(props) {
  const { nodes, materials } = useGLTF('/models/clancy.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} scale={[1, 0.5, 1]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[0, 1, 2.25]} rotation={[0.927, 0, 0]} scale={[1.5, 1, 1.25]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.002']} position={[0, 0, 2.19]} scale={[1.4, 1.4, 2]} />
    </group>
  )
}

useGLTF.preload('/models/clancy.glb')
