/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/operahouse.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function OperaHouse(props) {
  const { nodes, materials } = useGLTF('/models/operahouse.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.518, 0, 0.579]} rotation={[-Math.PI, 1.122, -Math.PI]} scale={[0.735, 0.809, 0.735]}>
        <group position={[0.25, 0.253, 0.129]} rotation={[0, -1.57, 3.142]} scale={[-2.839, -2.581, -2.839]}>
          <group position={[0.009, 0.022, 0.25]}>
            <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} position={[-0.116, -0.01, -0.302]} rotation={[-Math.PI / 2, 0, -0.183]} scale={[-0.111, -0.065, -0.141]} />
            <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[0.121, -0.006, -0.233]} rotation={[-Math.PI / 2, 0, 0.199]} scale={[-0.091, -0.054, -0.106]} />
            <group position={[-0.17, -0.001, -0.008]} rotation={[Math.PI / 2, 0, 0.183]} scale={[-0.342, -0.342, -0.376]}>
              <mesh geometry={nodes.Sphere003_1.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Sphere003_2.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Sphere003_3.geometry} material={materials['Kaca.002']} />
            </group>
            <group position={[0.17, 0.001, 0.008]} rotation={[Math.PI / 2, 0, -0.199]} scale={-0.281}>
              <mesh geometry={nodes.Sphere003_1.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Sphere003_2.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Sphere003_3.geometry} material={materials['Kaca.002']} />
            </group>
            <group position={[-0.192, -0.001, 0.109]} rotation={[Math.PI / 2, 0, 0.183]} scale={[-0.33, -0.255, -0.28]}>
              <mesh geometry={nodes.Sphere004_1.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Sphere004_2.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Sphere004_3.geometry} material={materials['Kaca.003']} />
            </group>
            <group position={[0.19, 0.001, 0.104]} rotation={[Math.PI / 2, 0, -0.199]} scale={[-0.271, -0.209, -0.209]}>
              <mesh geometry={nodes.Sphere004_1.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Sphere004_2.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Sphere004_3.geometry} material={materials['Kaca.003']} />
            </group>
            <group position={[-0.212, -0.001, 0.22]} rotation={[Math.PI / 2, 0, 0.183]} scale={[-0.269, -0.178, -0.196]}>
              <mesh geometry={nodes.Sphere007_1.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Sphere007_2.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Sphere007_3.geometry} material={materials['Kaca.002']} />
            </group>
            <group position={[0.208, 0.001, 0.195]} rotation={[Math.PI / 2, 0, -0.199]} scale={[-0.221, -0.146, -0.146]}>
              <mesh geometry={nodes.Sphere007_1.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Sphere007_2.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Sphere007_3.geometry} material={materials['Kaca.002']} />
            </group>
            <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.002']} position={[-0.08, -0.001, -0.496]} rotation={[Math.PI / 2, 0, -2.959]} scale={[-0.228, -0.203, -0.224]} />
            <mesh geometry={nodes.Sphere005.geometry} material={materials['Faacde.001']} position={[-0.111, 0.159, -0.328]} rotation={[2.577, 0.154, -3.048]} scale={[-0.294, -0.403, -0.288]} />
            <mesh geometry={nodes.Sphere006.geometry} material={materials['Faacde.001']} position={[-0.141, 0.08, -0.165]} rotation={[2.514, 0.147, -3.039]} scale={[-0.325, -0.272, -0.263]} />
            <mesh geometry={nodes.Sphere007.geometry} material={materials['Faacde.001']} position={[-0.177, 0.067, 0.029]} rotation={[2.707, 0.165, -3.068]} scale={[-0.345, -0.193, -0.181]} />
            <mesh geometry={nodes.Sphere008.geometry} material={materials['Material.001']} position={[-0.191, -0.1, -0.708]} rotation={[1.261, 0, 3.14]} scale={[-0.213, -0.215, -0.233]} />
            <mesh geometry={nodes.Sphere009.geometry} material={materials['Material.001']} position={[-0.191, -0.051, -0.496]} rotation={[1.728, 0, -0.001]} scale={[-0.165, -0.165, -0.181]} />
            <mesh geometry={nodes.Sphere010.geometry} material={nodes.Sphere010.material} position={[-0.191, 0.033, -0.613]} rotation={[0.559, 0.001, -0.001]} scale={[-0.136, -0.138, -0.132]} />
            <mesh geometry={nodes.Sphere011.geometry} material={materials['Kaca.002']} position={[-0.191, 0.054, -0.603]} rotation={[2.709, -0.001, 3.141]} scale={[-0.111, -0.12, -0.113]} />
            <mesh geometry={nodes.Sphere012.geometry} material={materials['Faacde.001']} position={[-0.188, -0.044, 0.09]} rotation={[2.284, 0.118, 0.134]} scale={[-0.352, -0.186, -0.188]} />
            <mesh geometry={nodes.Sphere013.geometry} material={materials['Material.003']} position={[-0.173, -0.002, 0.007]} rotation={[Math.PI / 2, 0, 0.183]} scale={[-0.342, -0.342, -0.376]} />
            <mesh geometry={nodes.Sphere014.geometry} material={materials['Material.003']} position={[-0.189, -0.017, 0.095]} rotation={[Math.PI / 2, 0, 0.183]} scale={[-0.316, -0.255, -0.28]} />
            <mesh geometry={nodes.Sphere015.geometry} material={materials['Material.001']} position={[-0.191, -0.09, -0.566]} rotation={[2.657, -0.001, -0.001]} scale={[-0.165, -0.178, -0.169]} />
            <mesh geometry={nodes.Sphere017.geometry} material={materials['Material.003']} position={[0.187, -0.011, 0.092]} rotation={[Math.PI / 2, 0, -0.199]} scale={[-0.26, -0.209, -0.209]} />
            <mesh geometry={nodes.Sphere018.geometry} material={materials['Material.003']} position={[0.173, 0, 0.021]} rotation={[Math.PI / 2, 0, -0.199]} scale={-0.281} />
            <mesh geometry={nodes.Sphere019.geometry} material={materials['Faacde.001']} position={[0.176, 0.052, 0.038]} rotation={[2.706, -0.181, 3.058]} scale={[-0.283, -0.146, -0.146]} />
            <mesh geometry={nodes.Sphere020.geometry} material={materials['Faacde.001']} position={[0.146, 0.067, -0.112]} rotation={[2.513, -0.162, 3.025]} scale={[-0.267, -0.209, -0.209]} />
            <mesh geometry={nodes.Sphere022.geometry} material={materials['Faacde.001']} position={[0.119, 0.126, -0.246]} rotation={[2.576, -0.169, 3.035]} scale={[-0.242, -0.309, -0.23]} />
            <mesh geometry={nodes.Sphere023.geometry} material={nodes.Sphere023.material} position={[0.089, 0.001, -0.392]} rotation={[Math.PI / 2, 0, 2.942]} scale={[-0.187, -0.167, -0.167]} />
          </group>
          <mesh geometry={nodes.Cube001.geometry} material={materials['Material.004']} position={[0, 0.004, 0]} rotation={[Math.PI, -0.001, 0]} scale={-0.317} />
          <mesh geometry={nodes.Cube005.geometry} material={materials['Material.004']} position={[0, -0.002, 0]} rotation={[Math.PI, -0.001, 0]} scale={-0.317} />
          <mesh geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[0, 0.004, 0]} rotation={[Math.PI, -0.001, 0]} scale={-0.317} />
          <mesh geometry={nodes.Cube007.geometry} material={materials['Material.004']} position={[0, 0.004, 0]} rotation={[Math.PI, -0.001, 0]} scale={-0.317} />
          <mesh geometry={nodes.Cube008.geometry} material={materials['Material.005']} position={[0, -0.002, 0]} rotation={[Math.PI, -0.001, 0]} scale={-0.317} />
          <mesh geometry={nodes.Cube009.geometry} material={materials['Material.005']} position={[-0.31, 0.001, -0.085]} rotation={[Math.PI, -0.001, 0]} scale={-0.043} />
          <mesh geometry={nodes.Cube010.geometry} material={materials['Material.005']} position={[-0.329, -0.004, 0.086]} rotation={[Math.PI, -0.001, 0]} scale={-0.005} />
          <mesh geometry={nodes.Cube014.geometry} material={materials['Material.005']} position={[-0.329, 0.042, 0.192]} rotation={[Math.PI, 0.503, 0]} scale={-0.043} />
          <mesh geometry={nodes.Cube015.geometry} material={materials['Material.005']} position={[-0.319, -0.004, 0.173]} rotation={[Math.PI, 0.503, 0]} scale={-0.043} />
          <mesh geometry={nodes.Cube016.geometry} material={materials['Material.005']} position={[-0.344, 0.024, 0.249]} rotation={[Math.PI, -0.001, 0]} scale={-0.317} />
          <mesh geometry={nodes.Cube017.geometry} material={materials['Material.005']} position={[-0.374, -0.004, 0.392]} rotation={[Math.PI, -0.001, 0]} scale={-0.043} />
          <mesh geometry={nodes.Cube018.geometry} material={materials['Material.005']} position={[-0.297, 0.018, -0.361]} rotation={[Math.PI, -0.001, 0]} scale={-0.043} />
          <mesh geometry={nodes.Cube019.geometry} material={materials['Material.005']} position={[-0.316, -0.004, -0.321]} rotation={[Math.PI, -0.001, 0]} scale={-0.005} />
          <mesh geometry={nodes.Cube025.geometry} material={materials['Material.005']} position={[0, -0.007, 0]} rotation={[Math.PI, -0.001, 0]} scale={-0.317} />
          <mesh geometry={nodes.Cube026.geometry} material={materials['Material.005']} position={[-0.212, 0.051, 0.514]} rotation={[Math.PI, -0.001, 0]} scale={-0.28} />
          <mesh geometry={nodes.Cube027.geometry} material={materials['Material.005']} position={[0, 0.002, 0]} rotation={[Math.PI, -0.001, 0]} scale={-0.317} />
          <mesh geometry={nodes.Cube028.geometry} material={materials['Material.005']} position={[0, 0.002, 0]} rotation={[Math.PI, -0.001, 0]} scale={-0.317} />
          <mesh geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[0.235, 0.075, 0.457]} rotation={[Math.PI, -0.396, 0]} scale={-0.212} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/operahouse.glb')
