/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scientia.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Scientia(props) {
  const { nodes, materials } = useGLTF('/models/scientia.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.right.geometry} material={materials['Material.009']} position={[5, 0, 0]} scale={[1, 0.75, 1.25]} />
      <mesh geometry={nodes.bridgefront.geometry} material={materials['Material.005']} position={[0, 2.5, 1.56]} scale={[6, 0.25, 1.2]} />
      <mesh geometry={nodes['bridge-mid'].geometry} material={materials['Material.006']} position={[0, 1.29, -0.65]} scale={[6, 0.25, 3.2]} />
      <mesh geometry={nodes['base-ceiling'].geometry} position={[0, 7.39, 0.992]} scale={[3, 0.094, 3.825]} >
				<meshPhongMaterial color="#45A9E0" opacity={.5} transparent />
			</mesh>
      <mesh geometry={nodes.base.geometry} position={[0, 0.39, -0.65]} scale={[2.475, 2.325, 1.6]} >
				<meshPhongMaterial color="#45A9E0" opacity={.5} transparent />
			</mesh>
      <mesh geometry={nodes['base-ceiling-mid'].geometry} material={materials['Material.004']} position={[0, 5.089, 0.992]} scale={[0.45, 0.1, 3.485]} />
      <mesh geometry={nodes.basetexture.geometry} material={materials.metal} position={[0, 0.39, -0.65]} scale={[2.475, 2.325, 1.6]} />
      <mesh geometry={nodes.right001.geometry} material={materials['Material.003']} position={[-5, 0, 0]} scale={[1, 0.75, 1.25]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[4, 1.987, 2.6]} rotation={[Math.PI / 2, 0, 0]} scale={[0.65, 1, 2.025]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.010']} position={[-4, 1.65, 2.6]} rotation={[Math.PI / 2, 0, 0]} scale={[0.65, 1, 2.7]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.007']} position={[0, -1.96, 2.35]} scale={[1, 1.014, 1]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.008']} position={[0, -1.96, 2.35]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.008']} position={[0, -1.96, 2.35]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials.silver} position={[0, -1.96, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.061, 0.25]} />
      <mesh geometry={nodes['frame1-l'].geometry} material={materials.metal} position={[-1.663, 5.922, 4.754]} rotation={[0, 0, -0.44]} scale={[1.46, 0.026, 0.065]} />
      <mesh geometry={nodes['frame1-r'].geometry} material={materials.metal} position={[1.663, 5.922, 4.754]} rotation={[0, 0, 0.44]} scale={[1.46, 0.026, 0.065]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.007']} position={[0, -1.96, -0.9]} scale={[1, 1.014, 1]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials['Material.008']} position={[0, -1.96, -0.9]} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials['Material.008']} position={[0, -1.96, -0.9]} />
    </group>
  )
}

useGLTF.preload('/models/scientia.glb')
