/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/models/thetoaster2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TheToaster2(props) {
  const { nodes, materials } = useGLTF('/models/thetoaster2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[0, 1.2, 0]} scale={[0.833, 1.029, 0.882]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[0, 4.2, 0]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.001']} position={[-1.05, 2.7, 1.45]} rotation={[-Math.PI, 1.571, 0]} scale={[-0.15, -1.5, -0.15]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.001']} position={[1.2, 1.2, 1.6]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.001']} position={[1.05, 2.7, -1.45]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.15, -1.5, -0.15]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.001']} position={[-1.2, 1.2, -1.6]} rotation={[0, -Math.PI / 2, 0]} scale={[0.15, 1.5, 0.15]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Material} position={[0.15, 4.75, 0]} scale={[0.56, 0.8, 0.571]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.009']} position={[0, 1.717, 0]} scale={[1.05, 0.05, 1.55]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.009']} position={[0, 2.333, 0]} scale={[1.05, 0.05, 1.55]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.009']} position={[0, 2.95, 0]} scale={[1.05, 0.05, 1.55]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.009']} position={[0, 3.567, 0]} scale={[1.05, 0.05, 1.55]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[0.15, 4.3, 0]} />
      <mesh geometry={nodes.Cube080.geometry} material={materials['Material.006']} scale={[0.9, 1, 1.4]} />
      <mesh geometry={nodes.Cube076.geometry} material={materials['Material.004']} position={[-1.1, 0, 1.6]} scale={[0.3, 0.5, 0.3]} />
      <mesh geometry={nodes.Cube065.geometry} material={materials['Material.004']} position={[-1.1, 0, -1.6]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.004']} position={[0, 0, 0.5]} scale={[1.2, 0.5, 0.1]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.004']} position={[0, 0, -0.5]} scale={[1.2, 0.5, 0.1]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.004']} position={[1.1, 0, -1.6]} rotation={[Math.PI, 0, Math.PI]} scale={[0.3, 0.5, 0.3]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.004']} position={[1.1, 0, 1.6]} rotation={[0, Math.PI / 2, 0]} scale={[0.3, 0.5, 0.3]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.007']} position={[0, 1, 0]} />
    </group>
  )
}

useGLTF.preload('/models/thetoaster2.glb')
