/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/thetoaster1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TheToaster1(props) {
  const { nodes, materials } = useGLTF('/models/thetoaster1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[0, 1.2, 0]} scale={[0.833, 1.029, 0.882]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[0, 4.905, 0.8]} scale={[0.96, 1, 1.067]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Material} position={[0, 4.301, -0.8]} scale={[0.96, 1, 0.8]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.009']} position={[0, 1.767, 0]} scale={[1.05, 0.05, 1.55]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.009']} position={[0, 2.383, 0]} scale={[1.05, 0.05, 1.55]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.009']} position={[0, 3, 0]} scale={[1.05, 0.05, 1.55]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.009']} position={[0, 3.617, 0]} scale={[1.05, 0.05, 1.55]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.007']} position={[0, 4.2, 0.875]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.006']} position={[0, 4.2, 0.125]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.003']} position={[-1.05, 3, 1.45]} rotation={[-Math.PI, 1.571, 0]} scale={[-0.15, -1.8, -0.15]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.004']} position={[0, 1, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.003']} position={[-1.05, 2.7, -1.45]} rotation={[0, -Math.PI / 2, 0]} scale={[0.15, 1.5, 0.15]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.003']} position={[1.05, 2.7, -1.45]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.15, -1.5, -0.15]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.003']} position={[1.05, 3, 1.45]} rotation={[0, Math.PI / 2, 0]} scale={[0.15, 1.8, 0.15]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.003']} position={[-1.05, 0.5, 1.45]} rotation={[-Math.PI, -1.571, 0]} scale={[0.15, 0.5, 0.15]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.003']} position={[-1.05, 0.5, -1.45]} rotation={[0, -Math.PI / 2, 0]} scale={[0.15, 0.5, 0.15]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.003']} position={[1.05, 0.5, -1.45]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.15, 0.5, 0.15]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.003']} position={[1.05, 0.5, 1.45]} rotation={[0, Math.PI / 2, 0]} scale={[0.15, 0.5, 0.15]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.009']} position={[0, 4.233, 1.43]} scale={[1.05, 0.05, 0.125]} />
    </group>
  )
}

useGLTF.preload('/models/thetoaster1.glb')
