/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/towerone.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TowerOne(props) {
  const { nodes, materials } = useGLTF('/models/towerone.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 4, 0]} scale={[1.167, 1, 1]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} scale={[0.98, 1.016, 0.871]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.003']} position={[0, 7.97, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.8, 16, 0.711]} />
    </group>
  )
}

useGLTF.preload('/models/towerone.glb')
